language: python
python:
  - "3.9"

dist: focal  # Use Ubuntu 20.04 (which has SQLite 3.31.1 by default)

# Install Python dependencies
install:
  - pip install -U pip
  - pip install -r requirements.txt

# Apply migrations and run tests
script:
  - python manage.py migrate
  - coverage run --source=polls manage.py test  # Run tests and measure coverage
  - black --check .
  - flake8

after_success:
  - coveralls  # Submit coverage report to Coveralls

branches:
  only:
    - main

# Deployment to Elastic Beanstalk
deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: "us-east-1"  # Your AWS region
  app: "ebdjango8"  # Your Elastic Beanstalk app name
  env: "Ebdjango8-env"  # Your Elastic Beanstalk environment name
  on:
    branch: main
  # Deploy only on the master branch