# Generated by Django 4.2.16 on 2024-10-01 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pollsapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="choice",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
